export interface Product {
  id: string
  slug: string
  name: string
  images: string[]
  priceOriginal: number
  priceDiscounted: number
  material: string
  color: string
  stones: string
  size: string
  category:string;
  metal: string;
  gender: "women" | "men" | "unisex"
  tags?: string[]
}

export const womenProducts: Product[] = [
  {
    id: "w1",
    slug: "golden-drop-earrings",
    name: "Golden Drop Earrings",
    images: ["/gold-earing.jpg"],
    priceOriginal: 2999,
    priceDiscounted: 2499,
    material: "Gold Plated",
    color: "Gold",
    stones: "Cubic Zirconia",
    size: "Medium",
    category: "earrings",
    metal: "Brass",
    gender: "women",
    tags: ["festive", "party", "wedding"],
  },
  {
    id: "w2",
    slug: "silver-charm-bracelet",
    name: "Silver Charm Bracelet",
    images: ["/silver-bracelet.jpg"],
    priceOriginal: 1899,
    priceDiscounted: 1599,
    material: "Sterling Silver",
    color: "Silver",
    stones: "None",
    size: "Adjustable",
    category: "silver",
    metal: "Silver",
    gender: "women",
    tags: ["casual", "everyday", "gift"],
  },
  {
    id: "w3",
    slug: "rose-gold-bangles",
    name: "Rose Gold Bangles Set",
    images: ["/rose-gold-bracelet.jpg"],
    priceOriginal: 3499,
    priceDiscounted: 2999,
    material: "Rose Gold Plated",
    color: "Rose Gold",
    stones: "Pearls",
    size: "Standard",
    category: "bangles",
    metal: "Brass",
    gender: "women",
    tags: ["party", "wedding", "elegant", "festive"],
  },
  {
    id: "w4",
    slug: "artificial-pearl-necklace",
    name: "Artificial Pearl Necklace",
    images: ["/pearl-necklace.jpg"],
    priceOriginal: 1299,
    priceDiscounted: 999,
    material: "Artificial Pearls",
    color: "White",
    stones: "Artificial Pearls",
    size: "18 inches",
    category: "artificial",
    metal: "Alloy",
    gender: "women",
    tags: ["classic", "elegant", "formal"],
  },
  {
    id: "w5",
    slug: "diamond-stud-earrings",
    name: "Diamond Stud Earrings",
    images: ["/diamong-stud-earing.jpg"],
    priceOriginal: 4999,
    priceDiscounted: 4299,
    material: "White Gold",
    color: "White Gold",
    stones: "Diamonds",
    size: "Small",
    category: "earrings",
    metal: "White Gold",
    gender: "women",
    tags: ["luxury", "everyday", "formal", "gift", "festive"],
  },
  {
    id: "w6",
    slug: "silver-anklet-chain",
    name: "Silver Anklet Chain",
    images: ["/silver-anklet.jpg"],
    priceOriginal: 899,
    priceDiscounted: 749,
    material: "Sterling Silver",
    color: "Silver",
    stones: "None",
    size: "9-10 inches",
    category: "silver",
    metal: "Silver",
    gender: "women",
    tags: ["casual", "beachwear", "everyday", "festive", "gift"],
  },
  {
    id: "w7",
    slug: "kundal-choker-set",
    name: "Kundan Choker Set",
    images: ["/kundan-chocker.jpg"],
    priceOriginal: 4500,
    priceDiscounted: 3899,
    material: "Kundan",
    color: "Gold",
    stones: "Glass Stones",
    size: "Adjustable",
    category: "artificial",
    metal: "Alloy",
    gender: "women",
    tags: ["wedding", "festive", "traditional"],
  },
  {
    id: "w8",
    slug: "oxidised-silver-jhumkas",
    name: "Oxidised Silver Jhumkas",
    images: ["/oxidised-silver-jhumka.jpg"],
    priceOriginal: 1200,
    priceDiscounted: 950,
    material: "Oxidised Silver",
    color: "Black Silver",
    stones: "None",
    size: "Large",
    category: "silver",
    metal: "Alloy",
    gender: "women",
    tags: ["boho", "casual", "ethnic"],
  },
  {
    id: "w9",
    slug: "enamel-art-bangle",
    name: "Enamel Art Bangle",
    images: ["https://picsum.photos/id/12/800/800"],
    priceOriginal: 1999,
    priceDiscounted: 1699,
    material: "Enamel",
    color: "Multicolor",
    stones: "None",
    size: "2.6",
    category: "bangles",
    metal: "Brass",
    gender: "women",
    tags: ["artistic", "party", "festive"],
  },
  {
    id: "w10",
    slug: "minimalist-silver-hoops",
    name: "Minimalist Silver Hoops",
    images: ["/minimalist-silver-hoops.jpg"],
    priceOriginal: 1100,
    priceDiscounted: 899,
    material: "Sterling Silver",
    color: "Silver",
    stones: "None",
    size: "Medium",
    category: "silver",
    metal: "Silver",
    gender: "women",
    tags: ["minimalist", "everyday", "office"],
  },
  {
    id: "art2",
    slug: "peacock-design-choker-set",
    name: "Peacock Design Choker Set",
    images: ["/peacock-desgin-choker.jpg"],
    priceOriginal: 3200,
    priceDiscounted: 2799,
    material: "Enamel & Faux Stones",
    color: "Gold & Blue",
    stones: "Cubic Zirconia",
    size: "Adjustable",
    category: "artificial",
    metal: "Brass",
    gender: "women",
    tags: ["party", "statement", "wedding", "festive"],
  },
  {
    id: "art4",
    slug: "polki-stone-drop-earrings",
    name: "Polki Stone Drop Earrings",
    images: ["/polki-drop-stone-earring.jpg"],
    priceOriginal: 1499,
    priceDiscounted: 1199,
    material: "Polki",
    color: "Gold",
    stones: "Uncut Polki Stones",
    size: "Medium",
    category: "artificial",
    metal: "Alloy",
    gender: "women",
    tags: ["ethnic", "festive", "traditional"],
  },
  {
    id: "w13",
    slug: "classic-leather-tote-bag",
    name: "Classic Leather Tote Bag",
    images: ["https://i.pinimg.com/1200x/f4/c2/e2/f4c2e2b925cc9cf2c92608f29c2112c9.jpg", "https://i.pinimg.com/736x/5c/f3/0f/5cf30fb9df423c821904dae855894f8f.jpg"],
    priceOriginal: 4500,
    priceDiscounted: 3999,
    material: "Faux Leather",
    color: "Tan",
    stones: "N/A",
    size: "Large",
    category: "bag",
    metal: "N/A",
    gender: "women",
    tags: ["work", "everyday", "classic", "gift"],
  },
  {
    id: "w14",
    slug: "chic-crossbody-handbag",
    name: "Chic Crossbody Handbag",
    images: ["https://i.pinimg.com/736x/b2/44/98/b24498aa608328e83b7745024ffb35e2.jpg", "https://i.pinimg.com/1200x/2e/32/9d/2e329dd423bffd5e5f063e9ecf9cf329.jpg"],
    priceOriginal: 2800,
    priceDiscounted: 2299,
    material: "PU Leather",
    color: "Black",
    stones: "N/A",
    size: "Medium",
    category: "bag",
    metal: "N/A",
    gender: "women",
    tags: ["casual", "party", "minimalist"],
  },
  {
    id: "w15",
    slug: "elegant-evening-clutch",
    name: "Elegant Evening Clutch",
    images: ["https://i.pinimg.com/1200x/4c/55/c6/4c55c6843b6852bcf07022be7803cb45.jpg"],
    priceOriginal: 1999,
    priceDiscounted: 1599,
    material: "Satin & Metal",
    color: "Silver",
    stones: "N/A",
    size: "Small",
    category: "bag",
    metal: "Alloy",
    gender: "women",
    tags: ["wedding", "party", "formal", "elegant", "festive"],
  },
  {
    id: "w16",
    slug: "trendy-shoulder-bag",
    name: "Trendy Shoulder Bag",
    images: ["https://i.pinimg.com/1200x/23/21/ae/2321ae21c4ee6e2546e467b28dfbeaa6.jpg","https://i.pinimg.com/1200x/cc/56/3e/cc563eddad0a305db9d5792c1bad061f.jpg"],
    priceOriginal: 3200,
    priceDiscounted: 2799,
    material: "Canvas & Faux Leather",
    color: "Beige",
    stones: "N/A",
    size: "Medium",
    category: "bag",
    metal: "N/A",
    gender: "women",
    tags: ["casual", "trendy", "everyday"],
  },
]

export const menProducts: Product[] = [
  // Men's products remain unchanged
]

export const gifts: Product[] = [
  // Gifts products remain unchanged
]

export const allProducts = [...womenProducts, ...menProducts, ...gifts]

// --- FIX START: Added reelsData for the new section ---
export const reelsData = [
  {
    reelId: "r1",
    reelVideo: "/reels/jewel-reel.mp4", // Replace with your actual image paths
    productId: "w3", 
  },
  {
    reelId: "r2",
    reelVideo: "/reels/jewel-reel.mp4",
    productId: "w2",
  },
  {
    reelId: "r3",
    reelVideo: "/reels/jewel-reel.mp4",
    productId: "w9",
  },
  {
    reelId: "r4",
    reelVideo: "/reels/jewel-reel.mp4",
    productId: "w4",
  },
  {
    reelId: "r5",
    reelVideo: "/reels/jewel-reel.mp4",
    productId: "w5",
  },
]
// --- FIX END ---

export const testimonials = [
  {
    id: 1,
    name: "Priya Sharma",
    rating: 5,
    text: "Absolutely stunning jewelry! The quality exceeded my expectations.",
    image: "/testimonial1.jpg",
  },
  {
    id: 2,
    name: "Rahul Gupta",
    rating: 5,
    text: "Love the modern designs. Great value for money.",
    image: "/testimonial3.jpg",
  },
  {
    id: 3,
    name: "Anita Desai",
    rating: 5,
    text: "Love the modern designs. Great value for money!",
    image: "/testimonial2.jpg",
  },
]