export interface Product {
  id: string
  slug: string
  name: string
  images: string[]
  priceOriginal: number
  priceDiscounted: number
  material: string
  color: string
  stones: string
  size: string
  category: "earrings" | "bangles" | "silver" | "artificial"
  metal: string
  gender: "women" | "men"
  tags?: string[] // The new 'tags' field is an optional array of strings
}

export const womenProducts: Product[] = [
  {
    id: "w1",
    slug: "golden-drop-earrings",
    name: "Golden Drop Earrings",
    images: ["/gold-earing.jpg"],
    priceOriginal: 2999,
    priceDiscounted: 2499,
    material: "Gold Plated",
    color: "Gold",
    stones: "Cubic Zirconia",
    size: "Medium",
    category: "earrings",
    metal: "Brass",
    gender: "women",
    tags: ["festive", "party", "wedding"],
  },
  {
    id: "w2",
    slug: "silver-charm-bracelet",
    name: "Silver Charm Bracelet",
    images: ["/silver-bracelet.jpg"],
    priceOriginal: 1899,
    priceDiscounted: 1599,
    material: "Sterling Silver",
    color: "Silver",
    stones: "None",
    size: "Adjustable",
    category: "silver",
    metal: "Silver",
    gender: "women",
    tags: ["casual", "everyday", "gift"],
  },
  {
    id: "w3",
    slug: "rose-gold-bangles",
    name: "Rose Gold Bangles Set",
    images: ["/rose-gold-bracelet.jpg"],
    priceOriginal: 3499,
    priceDiscounted: 2999,
    material: "Rose Gold Plated",
    color: "Rose Gold",
    stones: "Pearls",
    size: "Standard",
    category: "bangles",
    metal: "Brass",
    gender: "women",
    tags: ["party", "wedding", "elegant", "festive"],
  },
  {
    id: "w4",
    slug: "artificial-pearl-necklace",
    name: "Artificial Pearl Necklace",
    images: ["/pearl-necklace.jpg"],
    priceOriginal: 1299,
    priceDiscounted: 999,
    material: "Artificial Pearls",
    color: "White",
    stones: "Artificial Pearls",
    size: "18 inches",
    category: "artificial",
    metal: "Alloy",
    gender: "women",
    tags: ["classic", "elegant", "formal"],
  },
  {
    id: "w5",
    slug: "diamond-stud-earrings",
    name: "Diamond Stud Earrings",
    images: ["/diamong-stud-earing.jpg"],
    priceOriginal: 4999,
    priceDiscounted: 4299,
    material: "White Gold",
    color: "White Gold",
    stones: "Diamonds",
    size: "Small",
    category: "earrings",
    metal: "White Gold",
    gender: "women",
    tags: ["luxury", "everyday", "formal", "gift", "festive"],
  },
  {
    id: "w6",
    slug: "silver-anklet-chain",
    name: "Silver Anklet Chain",
    images: ["/silver-anklet.jpg"],
    priceOriginal: 899,
    priceDiscounted: 749,
    material: "Sterling Silver",
    color: "Silver",
    stones: "None",
    size: "9-10 inches",
    category: "silver",
    metal: "Silver",
    gender: "women",
    tags: ["casual", "beachwear", "everyday", "festive"],
  },
  // --- NEW WOMEN'S PRODUCTS ---
  {
    id: "w7",
    slug: "kundal-choker-set",
    name: "Kundan Choker Set",
    images: ["/kundan-chocker.jpg"],
    priceOriginal: 4500,
    priceDiscounted: 3899,
    material: "Kundan",
    color: "Gold",
    stones: "Glass Stones",
    size: "Adjustable",
    category: "artificial",
    metal: "Alloy",
    gender: "women",
    tags: ["wedding", "festive", "traditional"],
  },
  {
    id: "w8",
    slug: "oxidised-silver-jhumkas",
    name: "Oxidised Silver Jhumkas",
    images: ["/oxidised-silver-jhumka.jpg"],
    priceOriginal: 1200,
    priceDiscounted: 950,
    material: "Oxidised Silver",
    color: "Black Silver",
    stones: "None",
    size: "Large",
    category: "silver",
    metal: "Alloy",
    gender: "women",
    tags: ["boho", "casual", "ethnic"],
  },
  {
    id: "w9",
    slug: "enamel-art-bangle",
    name: "Enamel Art Bangle",
    images: ["https://picsum.photos/id/12/800/800"],
    priceOriginal: 1999,
    priceDiscounted: 1699,
    material: "Enamel",
    color: "Multicolor",
    stones: "None",
    size: "2.6",
    category: "bangles",
    metal: "Brass",
    gender: "women",
    tags: ["artistic", "party", "festive"],
  },
  {
    id: "w10",
    slug: "minimalist-silver-hoops",
    name: "Minimalist Silver Hoops",
    images: ["/minimalist-silver-hoops.jpg"],
    priceOriginal: 1100,
    priceDiscounted: 899,
    material: "Sterling Silver",
    color: "Silver",
    stones: "None",
    size: "Medium",
    category: "silver",
    metal: "Silver",
    gender: "women",
    tags: ["minimalist", "everyday", "office"],
  },
  {
    id: "art2",
    slug: "peacock-design-choker-set",
    name: "Peacock Design Choker Set",
    images: ["/peacock-desgin-choker.jpg"],
    priceOriginal: 3200,
    priceDiscounted: 2799,
    material: "Enamel & Faux Stones",
    color: "Gold & Blue",
    stones: "Cubic Zirconia",
    size: "Adjustable",
    category: "artificial",
    metal: "Brass",
    gender: "women",
    tags: ["party", "statement", "wedding", "festive"],
  },
  {
    id: "art4",
    slug: "polki-stone-drop-earrings",
    name: "Polki Stone Drop Earrings",
    images: ["/polki-drop-stone-earring.jpg"],
    priceOriginal: 1499,
    priceDiscounted: 1199,
    material: "Polki",
    color: "Gold",
    stones: "Uncut Polki Stones",
    size: "Medium",
    category: "artificial",
    metal: "Alloy",
    gender: "women",
    tags: ["ethnic", "festive", "traditional"],
  },
]

export const menProducts: Product[] = [
  {
    id: "m1",
    slug: "black-steel-watch",
    name: "Black Steel Watch",
    images: ["/men-black-watch.jpg"],
    priceOriginal: 5999,
    priceDiscounted: 4999,
    material: "Stainless Steel",
    color: "Black",
    stones: "None",
    size: "Standard",
    category: "artificial",
    metal: "Steel",
    gender: "men",
    tags: ["formal", "office", "everyday"],
  },
  {
    id: "m2",
    slug: "silver-chain-bracelet",
    name: "Silver Chain Bracelet",
    images: ["/silver-bracelet-men.jpg"],
    priceOriginal: 2499,
    priceDiscounted: 1999,
    material: "Sterling Silver",
    color: "Silver",
    stones: "None",
    size: "8 inches",
    category: "silver",
    metal: "Silver",
    gender: "men",
    tags: ["casual", "everyday", "gift"],
  },
  {
    id: "m3",
    slug: "gold-signet-ring",
    name: "Gold Signet Ring",
    images: ["/gold-ring-men.jpg"],
    priceOriginal: 3999,
    priceDiscounted: 3499,
    material: "Gold Plated",
    color: "Gold",
    stones: "None",
    size: "Adjustable",
    category: "artificial",
    metal: "Brass",
    gender: "men",
    tags: ["statement", "formal", "gift", "festive"],
  },
  {
    id: "m4",
    slug: "leather-bracelet",
    name: "Leather Bracelet",
    images: ["/leather-bracelet-men.jpg"],
    priceOriginal: 1299,
    priceDiscounted: 999,
    material: "Genuine Leather",
    color: "Brown",
    stones: "None",
    size: "Adjustable",
    category: "artificial",
    metal: "Steel",
    gender: "men",
    tags: ["casual", "rugged", "everyday"],
  },
  {
    id: "m5",
    slug: "titanium-cufflinks",
    name: "Titanium Cufflinks",
    images: ["/titanium-cufflinks-men.jpg"],
    priceOriginal: 2999,
    priceDiscounted: 2499,
    material: "Titanium",
    color: "Silver",
    stones: "None",
    size: "Standard",
    category: "artificial",
    metal: "Titanium",
    gender: "men",
    tags: ["formal", "office", "wedding", "festive"],
  },
  {
    id: "m6",
    slug: "silver-pendant-chain",
    name: "Silver Pendant Chain",
    images: ["/silver-chain-men.jpg"],
    priceOriginal: 1899,
    priceDiscounted: 1599,
    material: "Sterling Silver",
    color: "Silver",
    stones: "None",
    size: "22 inches",
    category: "silver",
    metal: "Silver",
    gender: "men",
    tags: ["casual", "everyday"],
  },
  // --- NEW MEN'S PRODUCTS ---
  {
    id: "m7",
    slug: "onyx-beaded-bracelet",
    name: "Onyx Beaded Bracelet",
    images: ["https://picsum.photos/id/20/800/800"],
    priceOriginal: 1599,
    priceDiscounted: 1299,
    material: "Onyx Beads",
    color: "Black",
    stones: "Onyx",
    size: "Adjustable",
    category: "artificial",
    metal: "None",
    gender: "men",
    tags: ["casual", "spiritual", "gift"],
  },
  {
    id: "m8",
    slug: "engravable-silver-tie-clip",
    name: "Engravable Silver Tie Clip",
    images: ["https://picsum.photos/id/21/800/800"],
    priceOriginal: 2200,
    priceDiscounted: 1899,
    material: "Sterling Silver",
    color: "Silver",
    stones: "None",
    size: "Standard",
    category: "silver",
    metal: "Silver",
    gender: "men",
    tags: ["formal", "wedding", "gift", "office"],
  },
  {
    id: "m9",
    slug: "braided-rope-chain",
    name: "Braided Rope Chain",
    images: ["https://picsum.photos/id/22/800/800"],
    priceOriginal: 3200,
    priceDiscounted: 2800,
    material: "Gold Plated",
    color: "Gold",
    stones: "None",
    size: "24 inches",
    category: "artificial",
    metal: "Brass",
    gender: "men",
    tags: ["statement", "party", "festive"],
  },
]

export const allProducts = [...womenProducts, ...menProducts]

export const testimonials = [
  {
    id: 1,
    name: "Priya Sharma",
    rating: 5,
    text: "Absolutely stunning jewelry! The quality exceeded my expectations.",
    image: "/testimonial1.jpg",
  },
  {
    id: 2,
    name: "Rahul Gupta",
    rating: 5,
    text: "Love the modern designs. Great value for money.",
    image: "/testimonial3.jpg",
  },
  {
    id: 3,
    name: "Anita Desai",
    rating: 5,
    text: "Love the modern designs. Great value for money!",
    image: "/testimonial2.jpg",
  },
]