export interface Product {
  _id: string
  slug: string
  name: string
  description?: string
  images: string[]
  video?: string
  stock: number
  originalPrice: number
  price: number
  type: string;
  gender: "women" | "men" | "unisex"
  tags?: string[]
  color?: string[]
  material?: string
  adminPackagingWeight?: string
  adminPackagingDimension?: string
  dimensions?: string
  stones?: string[]
  jewelleryCategory?: string
  materialType?: string
  size?: string[]

  // priceOriginal: number
  // priceDiscounted: number
  // category:string;
  // metal: string;
}

export interface OrderItem {
  productId: string;
  name: string;
  image: string;
  quantity: number;
  price: number; // Price at the time of purchase
}

// Defines the structure of a complete order
export interface Order {
  id: string;
  orderDate: string;
  status: 'Delivered' | 'Processing' | 'Shipped' | 'Cancelled';
  totalAmount: number;
  items: OrderItem[];
  trackingInfo?: TrackingInfo; // This is the new optional property
}
export interface TrackingInfo {
  provider: string; // e.g., 'Delhivery', 'BlueDart'
  status: string;
  location: string;
  trackingNumber: string;
  lastUpdated: string;
}


// export const womenProducts: Product[] = [
//   {
//     id: "w1",
//     slug: "golden-drop-earrings",
//     name: "Golden Drop Earrings",
//     images: ["/gold-earing.jpg"],
//     priceOriginal: 2999,
//     priceDiscounted: 2499,
//     price: 2499,
//     stock: 74,
//     material: "Gold Plated",
//     color: ["Gold"],
//     stones: ["Cubic Zirconia"],
//     size: ["Medium"],
//     category: "earrings",
//     metal: "Brass",
//     gender: "women",
//     type: "jewellery",
//     tags: ["festive", "party", "wedding"],
//   },
//   {
//     id: "w2",
//     slug: "silver-charm-bracelet",
//     name: "Silver Charm Bracelet",
//     images: ["/silver-bracelet.jpg"],
//     priceOriginal: 1899,
//     priceDiscounted: 1599,
//     price: 1599,
//     stock: 74,
//     material: "Sterling Silver",
//     color: ["Silver"],
//     stones: [],
//     size: ["Adjustable"],
//     category: "silver",
//     metal: "Silver",
//     gender: "women",
//     type: "jewellery",
//     tags: ["casual", "everyday", "gift"],
//   },
//   {
//     id: "w3",
//     slug: "rose-gold-bangles",
//     name: "Rose Gold Bangles Set",
//     images: ["/rose-gold-bracelet.jpg"],
//     priceOriginal: 3499,
//     priceDiscounted: 2999,
//     price: 2999,
//     stock: 74,
//     material: "Rose Gold Plated",
//     color: ["Rose Gold"],
//     stones: ["Pearls"],
//     size: ["Standard"],
//     category: "bangles",
//     metal: "Brass",
//     gender: "women",
//     type: "jewellery",
//     tags: ["party", "wedding", "elegant", "festive"],
//   },
//   {
//     id: "w4",
//     slug: "artificial-pearl-necklace",
//     name: "Artificial Pearl Necklace",
//     images: ["/pearl-necklace.jpg"],
//     priceOriginal: 1299,
//     priceDiscounted: 999,
//     price: 999,
//     stock: 74,
//     material: "Artificial Pearls",
//     color: ["White"],
//     stones: ["Artificial Pearls"],
//     size: ["18 inches"],
//     category: "artificial",
//     metal: "Alloy",
//     gender: "women",
//     type: "jewellery",
//     tags: ["classic", "elegant", "formal"],
//   },
//   {
//     id: "w5",
//     slug: "diamond-stud-earrings",
//     name: "Diamond Stud Earrings",
//     images: ["/diamong-stud-earing.jpg"],
//     priceOriginal: 4999,
//     priceDiscounted: 4299,
//     price: 4299,
//     stock: 74,
//     material: "White Gold",
//     color: ["White Gold"],
//     stones: ["Diamonds"],
//     size: ["Small"],
//     category: "earrings",
//     metal: "White Gold",
//     gender: "women",
//     type: "jewellery",
//     tags: ["luxury", "everyday", "formal", "gift", "festive"],
//   },
//   {
//     id: "w6",
//     slug: "silver-anklet-chain",
//     name: "Silver Anklet Chain",
//     images: ["/silver-anklet.jpg"],
//     priceOriginal: 899,
//     priceDiscounted: 749,
//     price: 749,
//     stock: 74,
//     material: "Sterling Silver",
//     color: ["Silver"],
//     stones: ["None"],
//     size: ["9-10 inches"],
//     category: "silver",
//     metal: "Silver",
//     gender: "women",   
//     type: "jewellery",
//     tags: ["casual", "beachwear", "everyday", "festive", "gift"],
//   },
//   {
//     id: "w7",
//     slug: "kundal-choker-set",
//     name: "Kundan Choker Set",
//     images: ["/kundan-chocker.jpg"],
//     priceOriginal: 4500,
//     priceDiscounted: 3899,
//     price: 3899,
//     stock: 74,
//     material: "Kundan",
//     color: ["Gold"],
//     stones: ["Glass Stones"],
//     size: ["Adjustable"],
//     category: "artificial",
//     metal: "Alloy",
//     gender: "women",
//     type: "jewellery",
//     tags: ["wedding", "festive", "traditional"],
//   },
//   {
//     id: "w8",
//     slug: "oxidised-silver-jhumkas",
//     name: "Oxidised Silver Jhumkas",
//     images: ["/oxidised-silver-jhumka.jpg"],
//     priceOriginal: 1200,
//     priceDiscounted: 950,
//     price: 950,
//     stock: 74,
//     material: "Oxidised Silver",
//     color: ["Black Silver"],
//     stones: [],
//     size: ["Large"],
//     category: "silver",
//     metal: "Alloy",
//     gender: "women",
//     type: "jewellery",
//     tags: ["boho", "casual", "ethnic"],
//   },
//   {
//     id: "w9",
//     slug: "enamel-art-bangle",
//     name: "Enamel Art Bangle",
//     images: ["https://picsum.photos/id/12/800/800"],
//     priceOriginal: 1999,
//     priceDiscounted: 1699,
//     price: 1699,
//     stock: 74,
//     material: "Enamel",
//     color: ["Multicolor"],
//     stones: [],
//     size: ["2.6"],
//     category: "bangles",
//     metal: "Brass",
//     type: "jewellery",
//     gender: "women",
//     tags: ["artistic", "party", "festive"],
//   },
//   {
//     id: "w10",
//     slug: "minimalist-silver-hoops",
//     name: "Minimalist Silver Hoops",
//     images: ["/minimalist-silver-hoops.jpg"],
//     priceOriginal: 1100,
//     priceDiscounted: 899,
//     price: 899,
//     stock: 74,
//     material: "Sterling Silver",
//     color: ["Silver"],
//     stones: [],
//     size: ["Medium"],
//     category: "silver",
//     metal: "Silver",
//     gender: "women",
//     type: "jewellery",
//     tags: ["minimalist", "everyday", "office"],
//   },
//   {
//     id: "art2",
//     slug: "peacock-design-choker-set",
//     name: "Peacock Design Choker Set",
//     images: ["/peacock-desgin-choker.jpg"],
//     priceOriginal: 3200,
//     priceDiscounted: 2799,
//     price: 2799,
//     stock: 74,
//     material: "Enamel & Faux Stones",
//     color: ["Gold", "Blue"],
//     stones: ["Cubic Zirconia"],
//     size: ["Adjustable"],
//     category: "artificial",
//     metal: "Brass",
//     gender: "women",
//     type: "jewellery",
//     tags: ["party", "statement", "wedding", "festive"],
//   },
//   {
//     id: "art4",
//     slug: "polki-stone-drop-earrings",
//     name: "Polki Stone Drop Earrings",
//     images: ["/polki-drop-stone-earring.jpg"],
//     priceOriginal: 1499,
//     priceDiscounted: 1199,
//     price: 1199,
//     stock: 74,
//     material: "Polki",
//     color: ["Gold"],
//     stones: ["Uncut Polki Stones"],
//     size: ["Medium"],
//     category: "artificial",
//     metal: "Alloy",
//     gender: "women",
//     type: "jewellery",
//     tags: ["ethnic", "festive", "traditional"],
//   },
//   {
//     id: "w13",
//     slug: "classic-leather-tote-bag",
//     name: "Classic Leather Tote Bag",
//     images: ["https://i.pinimg.com/1200x/f4/c2/e2/f4c2e2b925cc9cf2c92608f29c2112c9.jpg", "https://i.pinimg.com/736x/5c/f3/0f/5cf30fb9df423c821904dae855894f8f.jpg"],
//     priceOriginal: 4500,
//     priceDiscounted: 3999,
//     price: 3999,
//     stock: 74,
//     material: "Faux Leather",
//     color: ["Tan"],
//     // stones: "N/A",
//     size: ["Large"],
//     category: "bag",
//     metal: "N/A",
//     gender: "women",
//     type: "jewellery",
//     tags: ["work", "everyday", "classic", "gift"],
//   },
//   {
//     id: "w14",
//     slug: "chic-crossbody-handbag",
//     name: "Chic Crossbody Handbag",
//     images: ["https://i.pinimg.com/736x/b2/44/98/b24498aa608328e83b7745024ffb35e2.jpg", "https://i.pinimg.com/1200x/2e/32/9d/2e329dd423bffd5e5f063e9ecf9cf329.jpg"],
//     priceOriginal: 2800,
//     priceDiscounted: 2299,
//     price: 2299,
//     stock: 74,
//     material: "PU Leather",
//     color: ["Black"],
//     // stones: "N/A",
//     size: ["Medium"],
//     category: "bag",
//     metal: "N/A",
//     gender: "women",
//     type: "jewellery",
//     tags: ["casual", "party", "minimalist"],
//   },
//   {
//     id: "w15",
//     slug: "elegant-evening-clutch",
//     name: "Elegant Evening Clutch",
//     images: ["https://i.pinimg.com/1200x/4c/55/c6/4c55c6843b6852bcf07022be7803cb45.jpg"],
//     priceOriginal: 1999,
//     priceDiscounted: 1599,
//     price: 1599,
//     stock: 74,
//     material: "Satin & Metal",
//     color: ["Silver"],
//     // stones: "N/A",
//     size: ["Small"],
//     category: "bag",
//     metal: "Alloy",
//     gender: "women",
//     type: "jewellery",
//     tags: ["wedding", "party", "formal", "elegant", "festive"],
//   },
//   {
//     id: "w16",
//     slug: "trendy-shoulder-bag",
//     name: "Trendy Shoulder Bag",
//     images: ["https://i.pinimg.com/1200x/23/21/ae/2321ae21c4ee6e2546e467b28dfbeaa6.jpg","https://i.pinimg.com/1200x/cc/56/3e/cc563eddad0a305db9d5792c1bad061f.jpg"],
//     priceOriginal: 3200,
//     priceDiscounted: 2799,
//     price: 2799,
//     stock: 74,
//     material: "Canvas & Faux Leather",
//     color: ["Beige"],
//     // stones: "N/A",
//     size: ["Medium"],
//     category: "bag",
//     metal: "N/A",
//     gender: "women",
//     type: "jewellery",
//     tags: ["casual", "trendy", "everyday"],
//   },
// ]

// // --- FIX START: Restored menProducts array ---
// export const menProducts: Product[] = [
//   {
//     id: "m1",
//     slug: "black-steel-watch",
//     name: "Black Steel Watch",
//     images: ["/men-black-watch.jpg"],
//     priceOriginal: 5999,
//     priceDiscounted: 4999,
//     price: 3999,
//     stock: 74,
//     material: "Stainless Steel",
//     color: ["Black"],
//     // stones: "None",
//     size: ["Standard"],
//     category: "artificial",
//     metal: "Steel",
//     gender: "men",
//     type: "jewellery",
//     tags: ["formal", "office", "everyday"],
//   },
//   {
//     id: "m2",
//     slug: "silver-chain-bracelet",
//     name: "Silver Chain Bracelet",
//     images: ["/silver-bracelet-men.jpg"],
//     priceOriginal: 2499,
//     priceDiscounted: 1999,
//     price: 3999,
//     stock: 74,
//     material: "Sterling Silver",
//     color: ["Silver"],
//     // stones: "None",
//     size: ["8 inches"],
//     category: "silver",
//     metal: "Silver",
//     gender: "men",
//     type: "jewellery",
//     tags: ["casual", "everyday", "gift"],
//   },
//   {
//     id: "m3",
//     slug: "gold-signet-ring",
//     name: "Gold Signet Ring",
//     images: ["/gold-ring-men.jpg"],
//     priceOriginal: 3999,
//     priceDiscounted: 3499,
//     price: 3999,
//     stock: 74,
//     material: "Gold Plated",
//     color: ["Gold"],
//     // stones: "None",
//     size: ["Adjustable"],
//     category: "artificial",
//     metal: "Brass",
//     gender: "men",
//     type: "jewellery",
//     tags: ["statement", "formal", "gift", "festive"],
//   },
//   {
//     id: "m4",
//     slug: "leather-bracelet",
//     name: "Leather Bracelet",
//     images: ["/leather-bracelet-men.jpg"],
//     priceOriginal: 1299,
//     priceDiscounted: 999,
//     price: 3999,
//     stock: 74,
//     material: "Genuine Leather",
//     color: ["Brown"],
//     // stones: "None",
//     size: ["Adjustable"],
//     category: "artificial",
//     metal: "Steel",
//     gender: "men",
//     type: "jewellery",
//     tags: ["casual", "rugged", "everyday"],
//   },
//   {
//     id: "m5",
//     slug: "titanium-cufflinks",
//     name: "Titanium Cufflinks",
//     images: ["/titanium-cufflinks-men.jpg"],
//     priceOriginal: 2999,
//     priceDiscounted: 2499,
//     price: 3999,
//     stock: 74,
//     material: "Titanium",
//     color: ["Silver"],
//     // stones: "None",
//     size: ["Standard"],
//     category: "artificial",
//     metal: "Titanium",
//     gender: "men",
//     type: "jewellery",
//     tags: ["formal", "office", "wedding", "festive"],
//   },
//   {
//     id: "m6",
//     slug: "silver-pendant-chain",
//     name: "Silver Pendant Chain",
//     images: ["/silver-chain-men.jpg"],
//     priceOriginal: 1899,
//     priceDiscounted: 1599,
//     price: 3999,
//     stock: 74,
//     material: "Sterling Silver",
//     color: ["Silver"],
//     // stones: "None",
//     size: ["22 inches"],
//     category: "silver",
//     metal: "Silver",
//     gender: "men",
//     type: "jewellery",
//     tags: ["casual", "everyday"],
//   },
//   {
//     id: "m7",
//     slug: "onyx-beaded-bracelet",
//     name: "Onyx Beaded Bracelet",
//     images: ["https://i.pinimg.com/1200x/bc/26/b1/bc26b14d20e8399f0a8dd0416655b783.jpg"],
//     priceOriginal: 1599,
//     priceDiscounted: 1299,
//     price: 3999,
//     stock: 74,
//     material: "Onyx Beads",
//     color: ["Black"],
//     stones: ["Onyx"],
//     size: ["Adjustable"],
//     category: "artificial",
//     metal: "None",
//     gender: "men",
//     type: "jewellery",
//     tags: ["casual", "spiritual", "gift"],
//   },
//   {
//     id: "m9",
//     slug: "braided-rope-chain",
//     name: "Braided Rope Chain",
//     images: ["https://i.pinimg.com/1200x/f9/2b/d8/f92bd85179adb8cc97073ddebc08566d.jpg"],
//     priceOriginal: 3200,
//     priceDiscounted: 2800,
//     price: 3999,
//     stock: 74,
//     material: "Gold Plated",
//     color: ["Gold"],
//     // stones: "None",
//     size: ["24 inches"],
//     category: "artificial",
//     metal: "Brass",
//     gender: "men",
//     type: "jewellery",
//     tags: ["statement", "party", "festive"],
//   },
//   {
//     id: "m8",
//     slug: "engravable-silver-tie-clip",
//     name: "Engravable Silver Tie Clip",
//     images: ["/engravable-silver-tie-clip.jpg"],
//     priceOriginal: 2200,
//     priceDiscounted: 1899,
//     price: 3999,
//     stock: 74,
//     material: "Sterling Silver",
//     color: ["Silver"],
//     // stones: "None",
//     size: ["Standard"],
//     category: "silver",
//     metal: "Silver",
//     gender: "men",
//     type: "jewellery",
//     tags: ["formal", "wedding", "gift", "office"],
//   },
//   {
//     id: "m10",
//     slug: "classic-silver-band-ring",
//     name: "Classic Silver Band Ring",
//     images: ["/classic-silver-band.jpg"],
//     priceOriginal: 1999,
//     priceDiscounted: 1699,
//     price: 3999,
//     stock: 74,
//     material: "Sterling Silver",
//     color: ["Silver"],
//     // stones: "None",
//     size: ["Multiple Sizes"],
//     category: "silver",
//     metal: "Silver",
//     gender: "men",
//     type: "jewellery",
//     tags: ["minimalist", "everyday", "formal", "gift"],
//   },
//   {
//     id: "m11",
//     slug: "men-silver-stud-earring",
//     name: "Men's Silver Stud Earring",
//     images: ["https://picsum.photos/id/31/800/800"],
//     priceOriginal: 999,
//     priceDiscounted: 799,
//     price: 3999,
//     stock: 74,
//     material: "Sterling Silver",
//     color: ["Silver"],
//     // stones: "None",
//     size: ["Small"],
//     category: "silver",
//     metal: "Silver",
//     gender: "men",
//     type: "jewellery",
//     tags: ["casual", "minimalist", "everyday", "statement"],
//   },
//   {
//     id: "m12",
//     slug: "geometric-silver-pendant",
//     name: "Geometric Silver Pendant",
//     images: ["https://i.pinimg.com/1200x/5c/2d/08/5c2d084dde9fe0f7c6ee3a70a1c781cb.jpg"],
//     priceOriginal: 2199,
//     priceDiscounted: 1799,
//     price: 3999,
//     stock: 74,
//     material: "Sterling Silver",
//     color: ["Silver"],
//     // stones: "None",
//     size: ["20 inches"],
//     category: "silver",
//     metal: "Silver",
//     gender: "men",
//     type: "jewellery",
//     tags: ["statement", "modern", "casual"],
//   },
// ]
// // --- FIX END ---

// // --- FIX START: Restored gifts array ---
// export const gifts: Product[] = [
//   {
//     id: "g1",
//     slug: "lakshmi-ganesh-silver-murti",
//     name: "Lakshmi Ganesh Silver Murti",
//     images: ["/lakshmi-ganesh-murti.jpg"],
//     priceOriginal: 7999,
//     priceDiscounted: 6999,
//     price: 6999,
//     stock: 74,
//     material: "925 Sterling Silver",
//     color: ["Silver"],
//     // stones: "N/A",
//     size: ["4 inches"],
//     category: "gift",
//     metal: "Silver",
//     gender: "unisex",
//     type: "gift",

//     tags: ["divine", "festive", "diwali", "wedding-gift", "housewarming"],
//   },
//   {
//     id: "g2",
//     slug: "womens-festive-gift-box",
//     name: "Women's Festive Gift Box",
//     images: ["/women-gift-box.jpg"],
//     priceOriginal: 3999,
//     priceDiscounted: 3499,
//     price: 3499,
//     stock: 74,
//     material: "Assorted",
//     color: ["Multicolor"],
//     // stones: "Assorted",
//     size: ["Box Set"],
//     category: "gift",
//     metal: "Alloy",
//     type: "gift",
//     gender: "women",
//     tags: ["gift-box", "festive", "birthday", "for-her"],
//   },
//   {
//     id: "g3",
//     slug: "men-accessory-gift-box",
//     name: "Men's Accessory Gift Box",
//     images: ["/men-gift-box.jpg"],
//     priceOriginal: 4500,
//     priceDiscounted: 3999,
//     price: 3999,
//     stock: 74,
//     material: "Leather & Steel",
//     color: ["Brown", "Silver"],
//     // stones: "N/A",
//     size: ["Box Set"],
//     category: "gift",
//     metal: "Steel",
//     gender: "men",
//     type: "gift",
//     tags: ["gift-box", "birthday", "anniversary", "for-him"],
//   },
//   {
//     id: "g4",
//     slug: "silver-coin-10g",
//     name: "Silver Coin of Purity (10g)",
//     images: ["/silver-coin-10g.jpg"],
//     priceOriginal: 1200,
//     priceDiscounted: 999,
//     price: 999,
//     stock: 74,
//     material: "999 Fine Silver",
//     color: ["Silver"],
//     // stones: "N/A",
//     size: ["10g"],
//     category: "gift",
//     metal: "Silver",
//     gender: "unisex",
//     type: "gift",
//     tags: ["investment", "gift", "festive", "good-luck"],
//   },
// ]
// // --- FIX END ---

// export const allProducts = [...womenProducts, ...menProducts, ...gifts]

export const reelsData = [
  {
    reelId: "r1",
    reelVideo: "/reels/jewel-reel.mp4",
    productId: "w3", 
  },
  {
    reelId: "r2",
    reelVideo: "/reels/jewel-reel.mp4",
    productId: "w2",
  },
  {
    reelId: "r3",
    reelVideo: "/reels/jewel-reel.mp4",
    productId: "w9",
  },
  {
    reelId: "r4",
    reelVideo: "/reels/jewel-reel.mp4",
    productId: "w4",
  },
  {
    reelId: "r5",
    reelVideo: "/reels/jewel-reel.mp4",
    productId: "w5",
  },
]

export const mockOrders: Order[] = [
  {
    id: 'ORD-2025-001',
    orderDate: '2025-08-15',
    status: 'Delivered',
    totalAmount: 4299,
    items: [
      {
        productId: 'w5',
        name: 'Diamond Stud Earrings',
        image: '/diamong-stud-earing.jpg',
        quantity: 1,
        price: 4299,
      },
    ],
    trackingInfo: {
      provider: 'Delhivery',
      status: 'Delivered',
      location: 'Mumbai, MH',
      trackingNumber: '4076481000280',
      lastUpdated: '2025-08-18, 11:30:15 AM',
    },
  },
  {
    id: 'ORD-2025-002',
    orderDate: '2025-08-10',
    status: 'Processing',
    totalAmount: 3598,
    items: [
      {
        productId: 'm2',
        name: 'Silver Chain Bracelet',
        image: '/silver-bracelet-men.jpg',
        quantity: 1,
        price: 1999,
      },
      {
        productId: 'w2',
        name: 'Silver Charm Bracelet',
        image: '/silver-bracelet.jpg',
        quantity: 1,
        price: 1599,
      },
    ],
    trackingInfo: {
      provider: 'Delhivery',
      status: 'Manifested',
      location: 'Pune_Sudhwadi_GW (Maharashtra)',
      trackingNumber: '4076481000280',
      lastUpdated: '2025-08-19, 3:51:55 PM',
    },
  },
  {
    id: 'ORD-2025-003',
    orderDate: '2025-07-22',
    status: 'Cancelled',
    totalAmount: 999,
    items: [
      {
        productId: 'w4',
        name: 'Artificial Pearl Necklace',
        image: '/pearl-necklace.jpg',
        quantity: 1,
        price: 999,
      },
    ],
  },
];
// --- FIX END ---```

export const testimonials = [
  {
    id: 1,
    name: "Priya Sharma",
    rating: 5,
    text: "Absolutely stunning jewelry! The quality exceeded my expectations.",
    image: "/testimonial1.jpg",
  },
  {
    id: 2,
    name: "Rahul Gupta",
    rating: 5,
    text: "Love the modern designs. Great value for money.",
    image: "/testimonial3.jpg",
  },
  {
    id: 3,
    name: "Anita Desai",
    rating: 5,
    text: "Love the modern designs. Great value for money!",
    image: "/testimonial2.jpg",
  },
]